trigger:
  - develop
name: $(BuildID)

pool:
  name: Default

steps:
- task: Docker@2
  displayName: build and push image
  inputs:
    containerRegistry: 'RTU IT lAB Docker registry'
    repository: 'rtuitlab/games-launcher-back-develop'
    tags: |
     $(Build.BuildId)
     latest