version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: slyfoxy/gamecenter-backend:dev
    container_name: gamecenter-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: gamecenter-backend-db
    ports:
      - "5432:5432"
    env_file:
      - .env