version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: launcher-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:11.2-alpine
    container_name: launcher-db
    ports:
      - "5432:5432"
    env_file:
      - .env