version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: slyfoxy/gamecenter-backend:dev
    container_name: gamecenter-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    container_name: gamecenter-db
    env_file:
      - .env